/* test-vala-awn-dialog.c generated by valac, the Vala compiler
 * generated from test-vala-awn-dialog.vala, do not modify */

/*
 * Tests the Vala bindings for Awn.
 *
 * Copyright (C) 2007 Mark Lee <avant-wn@lazymalevolence.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA.
 *
 * Author : Mark Lee <avant-wn@lazymalevolence.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <libawn/libawn.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_AWN_TEST (awn_test_get_type ())
#define AWN_TEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_AWN_TEST, AwnTest))
#define AWN_TEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_AWN_TEST, AwnTestClass))
#define IS_AWN_TEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_AWN_TEST))
#define IS_AWN_TEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_AWN_TEST))
#define AWN_TEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_AWN_TEST, AwnTestClass))

typedef struct _AwnTest AwnTest;
typedef struct _AwnTestClass AwnTestClass;
typedef struct _AwnTestPrivate AwnTestPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _AwnTest {
	GtkWindow parent_instance;
	AwnTestPrivate * priv;
};

struct _AwnTestClass {
	GtkWindowClass parent_class;
};


static gpointer awn_test_parent_class = NULL;

GType awn_test_get_type (void);
enum  {
	AWN_TEST_DUMMY_PROPERTY
};
static gboolean awn_test_on_quit (AwnTest* self, GtkWidget* widget, GdkEvent* event);
static gboolean _awn_test_on_quit_gtk_widget_delete_event (GtkWidget* _sender, GdkEvent* event, gpointer self);
AwnTest* awn_test_new (void);
AwnTest* awn_test_construct (GType object_type);
static void awn_test_on_orient_clicked (GtkButton* button);
static void awn_test_on_attach_clicked (GtkButton* button);
static void _awn_test_on_orient_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void _awn_test_on_attach_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
gint awn_test_main (char** args, int args_length1);



static gboolean _awn_test_on_quit_gtk_widget_delete_event (GtkWidget* _sender, GdkEvent* event, gpointer self) {
	return awn_test_on_quit (self, _sender, event);
}


AwnTest* awn_test_construct (GType object_type) {
	GParameter * __params;
	GParameter * __params_it;
	GtkLabel* label;
	AwnTest * self;
	GtkLabel* _tmp0_;
	__params = g_new0 (GParameter, 1);
	__params_it = __params;
	label = NULL;
	__params_it->name = "type";
	g_value_init (&__params_it->value, GTK_TYPE_WINDOW_TYPE);
	g_value_set_enum (&__params_it->value, GTK_WINDOW_TOPLEVEL);
	__params_it++;
	self = g_object_newv (object_type, __params_it - __params, __params);
	gtk_window_set_title ((GtkWindow*) self, "Awn Dialog Test (Vala)");
	g_signal_connect_object ((GtkWidget*) self, "delete-event", (GCallback) _awn_test_on_quit_gtk_widget_delete_event, self, 0);
	label = (_tmp0_ = g_object_ref_sink ((GtkLabel*) gtk_label_new ("One of the dialogs points to this window.")), _g_object_unref0 (label), _tmp0_);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) label);
	gtk_widget_show_all ((GtkWidget*) self);
	_g_object_unref0 (label);
	while (__params_it > __params) {
		--__params_it;
		g_value_unset (&__params_it->value);
	}
	g_free (__params);
	return self;
}


AwnTest* awn_test_new (void) {
	return awn_test_construct (TYPE_AWN_TEST);
}


static gboolean awn_test_on_quit (AwnTest* self, GtkWidget* widget, GdkEvent* event) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (widget != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	gtk_main_quit ();
	result = TRUE;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void awn_test_on_orient_clicked (GtkButton* button) {
	AwnDialog* dialog;
	gint pos = 0;
	GtkPositionType _tmp0_;
	g_return_if_fail (button != NULL);
	dialog = _g_object_ref0 (AWN_DIALOG (gtk_widget_get_parent ((GtkWidget*) gtk_widget_get_parent ((GtkWidget*) gtk_widget_get_parent ((GtkWidget*) button)))));
	pos = (gint) (g_object_get (dialog, "position", &_tmp0_, NULL), _tmp0_);
	pos = (pos + 1) % 4;
	g_object_set (dialog, "position", (GtkPositionType) pos, NULL);
	_g_object_unref0 (dialog);
}


static void awn_test_on_attach_clicked (GtkButton* button) {
	AwnDialog* dialog;
	gboolean _tmp0_;
	g_return_if_fail (button != NULL);
	dialog = _g_object_ref0 (AWN_DIALOG (gtk_widget_get_parent ((GtkWidget*) gtk_widget_get_parent ((GtkWidget*) gtk_widget_get_parent ((GtkWidget*) button)))));
	g_object_set (dialog, "anchored", !(g_object_get (dialog, "anchored", &_tmp0_, NULL), _tmp0_), NULL);
	_g_object_unref0 (dialog);
}


static void _awn_test_on_orient_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	awn_test_on_orient_clicked (_sender);
}


static void _awn_test_on_attach_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	awn_test_on_attach_clicked (_sender);
}


gint awn_test_main (char** args, int args_length1) {
	gint result;
	AwnDialog* dialog;
	AwnTest* window;
	AwnDialog* dialog2;
	GtkButton* orient;
	GtkButton* attach;
	AwnDialog* _tmp0_;
	AwnTest* _tmp1_;
	AwnDialog* _tmp2_;
	GtkButton* _tmp3_;
	GtkButton* _tmp4_;
	dialog = NULL;
	window = NULL;
	dialog2 = NULL;
	orient = NULL;
	attach = NULL;
	gtk_init (&args_length1, &args);
	dialog = (_tmp0_ = g_object_ref_sink ((AwnDialog*) awn_dialog_new ()), _g_object_unref0 (dialog), _tmp0_);
	gtk_window_set_title ((GtkWindow*) dialog, "Hello");
	gtk_widget_show_all ((GtkWidget*) dialog);
	window = (_tmp1_ = g_object_ref_sink (awn_test_new ()), _g_object_unref0 (window), _tmp1_);
	dialog2 = (_tmp2_ = g_object_ref_sink ((AwnDialog*) awn_dialog_new_for_widget ((GtkWidget*) window)), _g_object_unref0 (dialog2), _tmp2_);
	gtk_window_set_title ((GtkWindow*) dialog2, "Another Title");
	gtk_widget_set_size_request ((GtkWidget*) dialog2, -1, 200);
	orient = (_tmp3_ = g_object_ref_sink ((GtkButton*) gtk_button_new_with_label ("Change orientation")), _g_object_unref0 (orient), _tmp3_);
	g_signal_connect (orient, "clicked", (GCallback) _awn_test_on_orient_clicked_gtk_button_clicked, NULL);
	gtk_container_add ((GtkContainer*) dialog2, (GtkWidget*) orient);
	attach = (_tmp4_ = g_object_ref_sink ((GtkButton*) gtk_button_new_with_label ("Toggle dialog attach")), _g_object_unref0 (attach), _tmp4_);
	g_signal_connect (attach, "clicked", (GCallback) _awn_test_on_attach_clicked_gtk_button_clicked, NULL);
	gtk_container_add ((GtkContainer*) dialog2, (GtkWidget*) attach);
	gtk_widget_show_all ((GtkWidget*) dialog2);
	gtk_main ();
	result = 0;
	_g_object_unref0 (dialog);
	_g_object_unref0 (window);
	_g_object_unref0 (dialog2);
	_g_object_unref0 (orient);
	_g_object_unref0 (attach);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return awn_test_main (argv, argc);
}


static void awn_test_class_init (AwnTestClass * klass) {
	awn_test_parent_class = g_type_class_peek_parent (klass);
}


static void awn_test_instance_init (AwnTest * self) {
}


GType awn_test_get_type (void) {
	static GType awn_test_type_id = 0;
	if (awn_test_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (AwnTestClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) awn_test_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AwnTest), 0, (GInstanceInitFunc) awn_test_instance_init, NULL };
		awn_test_type_id = g_type_register_static (GTK_TYPE_WINDOW, "AwnTest", &g_define_type_info, 0);
	}
	return awn_test_type_id;
}




